<a href="https://colab.research.google.com/github/Inder01Official/teachaimanners/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#in this we are going to learn some of most fundatmental concept of tensors using tensorflow
what covers in this:
* introduction to tensors
* get info from tensors
* manipulating tensors
* tensors and numpy
* useing @tf.function (way to speed up)
* using GPU with Tensorflow
* exercises for this

In [1]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [5]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check the number of dimension of tensior (ndim stands for no. of dimensions)
scalar.ndim

0

In [7]:
# Create a Vector
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# change the dim of our vector
vector.ndim

1

In [11]:
#Create a metrix(it has more then 1 dim)
matrix = tf.constant([[10 , 7],
                     [ 7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
#create other matrix
ant_matrix = tf.constant([[10.,7.],
                          [3.,2.],
                          [8.,9.]], dtype = tf.float16) # specify the data type with d type perameter
ant_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
#whats the no. of dim of ant_matrix
ant_matrix.ndim

2

In [17]:
#create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [18]:
tensor.ndim

3

### creating tensors with tf.Variable

In [20]:
# create same tensor with tf.Variable() as above
chageable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
chageable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)